#!/usr/bin/env bash

curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo usermod -aG docker $USER

sudo apt install snapd

# echo " cgroup_enable=memory cgroup_memory=1" >> sudo /boot/cmdline.txt
sudo sed -i '$ s/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1/' /boot/cmdline.txt
sudo snap install microk8s --classic --channel=1.25
sudo usermod -a -G microk8s $USER
sudo snap install kubectl --classic 
sudo microk8s config > ~/.kube/config
sudo microk8s.enable registry
sudo microk8s.enable ingress
sudo microk8s enable cert-manager
sudo microk8s join 192.168.1.104:25000/18b685dd8f9702c0862758f3366425e0/666909b1e6cd --worker
# follow steps here to add grpc port 50051 https://microk8s.io/docs/addon-ingress

curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh

helm repo add k8ssandra https://helm.k8ssandra.io/stable
helm repo add jetstack https://charts.jetstack.io
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

pip install -U cqlsh
wget https://dl.google.com/go/go1.16.7.linux-arm64.tar.gz
sudo tar -C /usr/local/ -xzf go1.16.7.linux-arm64.tar.gz
rm go1.16.7.linux-arm64.tar.gz 


# after steps
# init c vault db after portforwarding postgres
# export PGPASSWORD=$(kubectl get secret --namespace default postgres-postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
# echo "CREATE DATABASE cel_vault;" | psql -U postgres -h 127.0.0.1
