apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-buffer
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-buffer
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/app/updateBuffer"]
            env:
              {{- include "helpers.list-env-variables" . | indent 12 }}
          restartPolicy: Never