// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/users.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Url                  string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Tags                 []string             `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Source               string               `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Post) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Post) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AddUserRequest struct {
	MastadonId           string   `protobuf:"bytes,2,opt,name=mastadon_id,json=mastadonId,proto3" json:"mastadon_id,omitempty"`
	MastadonUsername     string   `protobuf:"bytes,3,opt,name=mastadon_username,json=mastadonUsername,proto3" json:"mastadon_username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{1}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetMastadonId() string {
	if m != nil {
		return m.MastadonId
	}
	return ""
}

func (m *AddUserRequest) GetMastadonUsername() string {
	if m != nil {
		return m.MastadonUsername
	}
	return ""
}

type UserBaseResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBaseResponse) Reset()         { *m = UserBaseResponse{} }
func (m *UserBaseResponse) String() string { return proto.CompactTextString(m) }
func (*UserBaseResponse) ProtoMessage()    {}
func (*UserBaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{2}
}

func (m *UserBaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBaseResponse.Unmarshal(m, b)
}
func (m *UserBaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBaseResponse.Marshal(b, m, deterministic)
}
func (m *UserBaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBaseResponse.Merge(m, src)
}
func (m *UserBaseResponse) XXX_Size() int {
	return xxx_messageInfo_UserBaseResponse.Size(m)
}
func (m *UserBaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserBaseResponse proto.InternalMessageInfo

func (m *UserBaseResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserBaseResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPostRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{3}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{4}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "ffv.Post")
	proto.RegisterType((*AddUserRequest)(nil), "ffv.AddUserRequest")
	proto.RegisterType((*UserBaseResponse)(nil), "ffv.UserBaseResponse")
	proto.RegisterType((*GetPostRequest)(nil), "ffv.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "ffv.GetPostResponse")
}

func init() { proto.RegisterFile("users/users.proto", fileDescriptor_b48c37af7f888781) }

var fileDescriptor_b48c37af7f888781 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0xaf, 0x93, 0x40,
	0x10, 0xc7, 0xed, 0x03, 0x5f, 0xc3, 0x90, 0x3c, 0xfb, 0xd6, 0xaa, 0x84, 0xc4, 0xb4, 0xe1, 0x54,
	0x7f, 0x04, 0x4c, 0x4d, 0x34, 0x7a, 0xb2, 0xbd, 0x98, 0xde, 0x0c, 0xda, 0x8b, 0x07, 0x9b, 0x05,
	0x06, 0x4a, 0x2c, 0x5d, 0xdc, 0x1d, 0x48, 0xbc, 0xe8, 0xbf, 0x6e, 0x76, 0x59, 0x9a, 0xd4, 0x0b,
	0x99, 0xf9, 0xf2, 0x5d, 0x3e, 0xdf, 0x19, 0x16, 0xee, 0x3b, 0x85, 0x52, 0x25, 0xe6, 0x19, 0xb7,
	0x52, 0x90, 0x60, 0x4e, 0x59, 0xf6, 0xe1, 0xa2, 0x12, 0xa2, 0x3a, 0x61, 0x62, 0xa4, 0xac, 0x2b,
	0x13, 0xaa, 0x1b, 0x54, 0xc4, 0x9b, 0x76, 0x70, 0x45, 0x7f, 0xc1, 0xfd, 0x22, 0x14, 0xb1, 0x19,
	0x38, 0x9d, 0x3c, 0x05, 0x93, 0xe5, 0x64, 0xe5, 0xa5, 0xba, 0x64, 0x0c, 0x5c, 0xe2, 0x95, 0x0a,
	0x6e, 0x96, 0xce, 0xca, 0x4b, 0x4d, 0xcd, 0x9e, 0xc2, 0xad, 0x12, 0x9d, 0xcc, 0x31, 0x70, 0x8c,
	0xd1, 0x76, 0xec, 0x03, 0x40, 0x2e, 0x91, 0x13, 0x16, 0x07, 0x4e, 0x81, 0xbb, 0x9c, 0xac, 0xfc,
	0x75, 0x18, 0x0f, 0xec, 0x78, 0x64, 0xc7, 0xdf, 0x46, 0x76, 0xea, 0x59, 0xf7, 0x86, 0xa2, 0x1f,
	0x70, 0xb7, 0x29, 0x8a, 0xbd, 0x42, 0x99, 0xe2, 0xaf, 0x0e, 0x15, 0xb1, 0x05, 0xf8, 0x0d, 0x57,
	0xc4, 0x0b, 0x71, 0x3e, 0xd4, 0x45, 0x70, 0x63, 0x48, 0x30, 0x4a, 0xbb, 0x82, 0xbd, 0x82, 0xfb,
	0x8b, 0x41, 0x4f, 0x7c, 0xe6, 0xcd, 0x18, 0x68, 0x36, 0xbe, 0xd8, 0x5b, 0x3d, 0xfa, 0x04, 0x33,
	0x5d, 0x6f, 0xb9, 0xc2, 0x14, 0x55, 0x2b, 0xce, 0x0a, 0xcd, 0x18, 0xc4, 0xa9, 0x53, 0x76, 0x5e,
	0xdb, 0xb1, 0x39, 0x3c, 0x44, 0x29, 0x85, 0xb4, 0xcc, 0xa1, 0x89, 0x5e, 0xc0, 0xdd, 0x67, 0x24,
	0xbd, 0xa5, 0x31, 0xe1, 0x33, 0x98, 0x6a, 0xae, 0x4e, 0x67, 0x3f, 0xa0, 0xdb, 0x5d, 0x11, 0xbd,
	0x81, 0x47, 0x17, 0xab, 0x65, 0x3d, 0x07, 0xb7, 0x15, 0x8a, 0x8c, 0xd1, 0x5f, 0x7b, 0x71, 0x59,
	0xf6, 0xb1, 0x31, 0x18, 0x79, 0xfd, 0x07, 0x7c, 0x1d, 0xef, 0x2b, 0xca, 0xbe, 0xce, 0x91, 0xbd,
	0x87, 0xa9, 0xdd, 0x06, 0x7b, 0x6c, 0xac, 0xd7, 0xbb, 0x09, 0x9f, 0x18, 0xf1, 0xff, 0x81, 0xa2,
	0x07, 0xec, 0x1d, 0x4c, 0x2d, 0xd9, 0x1e, 0xbc, 0x8e, 0x1c, 0xce, 0xaf, 0xc5, 0xf1, 0xdc, 0xf6,
	0xf5, 0xf7, 0x97, 0x47, 0xa2, 0x56, 0x7d, 0x4c, 0x92, 0xaa, 0xa6, 0x63, 0x97, 0xc5, 0xb9, 0x68,
	0x92, 0xa6, 0xce, 0x8f, 0xc8, 0x4f, 0x4d, 0xfd, 0x13, 0x7f, 0x67, 0x49, 0x59, 0xf6, 0xc3, 0xcd,
	0xca, 0x6e, 0xcd, 0xbf, 0x7c, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x95, 0x66, 0x94, 0x4d, 0x6f,
	0x02, 0x00, 0x00,
}
