// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/users.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Tags                 []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Likes                int32    `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Post) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

type AddUserRequest struct {
	MastodonId           string   `protobuf:"bytes,2,opt,name=mastodon_id,json=mastodonId,proto3" json:"mastodon_id,omitempty"`
	MastodonUsername     string   `protobuf:"bytes,3,opt,name=mastodon_username,json=mastodonUsername,proto3" json:"mastodon_username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{1}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetMastodonId() string {
	if m != nil {
		return m.MastodonId
	}
	return ""
}

func (m *AddUserRequest) GetMastodonUsername() string {
	if m != nil {
		return m.MastodonUsername
	}
	return ""
}

type AddUserResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{2}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserRequest struct {
	MastodonId           string   `protobuf:"bytes,1,opt,name=mastodon_id,json=mastodonId,proto3" json:"mastodon_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetMastodonId() string {
	if m != nil {
		return m.MastodonId
	}
	return ""
}

type UserBaseResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBaseResponse) Reset()         { *m = UserBaseResponse{} }
func (m *UserBaseResponse) String() string { return proto.CompactTextString(m) }
func (*UserBaseResponse) ProtoMessage()    {}
func (*UserBaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{4}
}

func (m *UserBaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBaseResponse.Unmarshal(m, b)
}
func (m *UserBaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBaseResponse.Marshal(b, m, deterministic)
}
func (m *UserBaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBaseResponse.Merge(m, src)
}
func (m *UserBaseResponse) XXX_Size() int {
	return xxx_messageInfo_UserBaseResponse.Size(m)
}
func (m *UserBaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserBaseResponse proto.InternalMessageInfo

func (m *UserBaseResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserBaseResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPostRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{5}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{6}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "ffv.user.Post")
	proto.RegisterType((*AddUserRequest)(nil), "ffv.user.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "ffv.user.AddUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "ffv.user.GetUserRequest")
	proto.RegisterType((*UserBaseResponse)(nil), "ffv.user.UserBaseResponse")
	proto.RegisterType((*GetPostRequest)(nil), "ffv.user.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "ffv.user.GetPostResponse")
}

func init() { proto.RegisterFile("users/users.proto", fileDescriptor_b48c37af7f888781) }

var fileDescriptor_b48c37af7f888781 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x9b, 0x2f, 0x3a, 0x91, 0xd2, 0x74, 0x85, 0x60, 0xe9, 0xa5, 0xd1, 0x9e, 0x42, 0x41,
	0xb6, 0x28, 0xe2, 0xc2, 0xa9, 0xf4, 0x82, 0x7a, 0x43, 0x41, 0xbd, 0x70, 0x00, 0x39, 0xf6, 0x38,
	0xb1, 0x1a, 0x7b, 0xcd, 0xce, 0x6c, 0x24, 0xfe, 0x03, 0xff, 0x8e, 0x3f, 0x84, 0x76, 0xd7, 0x0e,
	0x49, 0x05, 0xa8, 0x17, 0x6b, 0xdf, 0xcc, 0xdb, 0x37, 0x33, 0x6f, 0xc7, 0x70, 0x66, 0x09, 0x0d,
	0x25, 0xfe, 0x1b, 0x37, 0x46, 0xb3, 0x16, 0x4f, 0x8a, 0x62, 0x1b, 0xbb, 0xc0, 0xf9, 0xc5, 0x4a,
	0xeb, 0xd5, 0x06, 0x13, 0x1f, 0x5f, 0xda, 0x22, 0xe1, 0xb2, 0x42, 0xe2, 0xb4, 0x6a, 0x02, 0x55,
	0xfd, 0x8c, 0xa0, 0xff, 0x49, 0x13, 0x8b, 0x29, 0xf4, 0xac, 0xd9, 0xc8, 0x68, 0x16, 0xcd, 0x4f,
	0x16, 0xee, 0x28, 0x04, 0xf4, 0x39, 0x5d, 0x91, 0x3c, 0x9e, 0xf5, 0xe6, 0x27, 0x0b, 0x7f, 0x16,
	0xcf, 0x60, 0x48, 0xda, 0x9a, 0x0c, 0x65, 0xcf, 0x13, 0x5b, 0xe4, 0xe2, 0xa9, 0xe5, 0xb5, 0x36,
	0xb2, 0x1f, 0xe2, 0x01, 0x09, 0x09, 0xa3, 0x4c, 0xd7, 0x8c, 0x35, 0xcb, 0x81, 0x4f, 0x74, 0x50,
	0x3c, 0x85, 0xc1, 0xa6, 0xbc, 0x47, 0x92, 0xc3, 0x59, 0x34, 0x1f, 0x2c, 0x02, 0x50, 0x5f, 0x61,
	0xf2, 0x21, 0xcf, 0xef, 0x08, 0xcd, 0x02, 0xbf, 0x5b, 0x24, 0x16, 0x17, 0x30, 0xae, 0x52, 0x62,
	0x9d, 0xeb, 0xfa, 0x5b, 0x99, 0xcb, 0x63, 0xaf, 0x02, 0x5d, 0xe8, 0x36, 0x17, 0xaf, 0xe0, 0x6c,
	0x47, 0x70, 0x33, 0xd7, 0x69, 0xd5, 0x75, 0x37, 0xed, 0x12, 0x77, 0x6d, 0x5c, 0x5d, 0xc2, 0xe9,
	0x4e, 0x9f, 0x1a, 0x5d, 0x13, 0x8a, 0xe7, 0x30, 0x72, 0xd7, 0x9c, 0x78, 0x18, 0x7e, 0xe8, 0xe0,
	0x6d, 0xae, 0xde, 0xc0, 0xe4, 0x23, 0xf2, 0x7f, 0x7a, 0x89, 0x1e, 0xf6, 0xa2, 0xae, 0x61, 0xea,
	0xf8, 0x37, 0x29, 0xe1, 0x4e, 0xdf, 0x59, 0xc6, 0x29, 0x5b, 0xea, 0xe4, 0x03, 0x72, 0x06, 0xa0,
	0x31, 0xda, 0xb4, 0x23, 0x05, 0xa0, 0x5e, 0xfa, 0xa2, 0xee, 0x45, 0xba, 0xa2, 0xff, 0xec, 0xef,
	0x1d, 0x9c, 0xee, 0xa8, 0x6d, 0x2d, 0x05, 0xfd, 0x46, 0x13, 0x7b, 0xe2, 0xf8, 0x6a, 0x12, 0x77,
	0x7b, 0x10, 0x7b, 0x96, 0xcf, 0x5d, 0xfd, 0x8a, 0x60, 0xec, 0x9a, 0xfc, 0x8c, 0x66, 0x5b, 0x66,
	0x28, 0xae, 0x61, 0xd4, 0x5a, 0x22, 0xe4, 0x9f, 0x0b, 0x87, 0xaf, 0x70, 0xfe, 0xe2, 0x2f, 0x99,
	0x50, 0x53, 0x1d, 0x39, 0x85, 0xd6, 0xa8, 0x7d, 0x85, 0x43, 0xef, 0x1e, 0xa3, 0xe0, 0xf7, 0xf0,
	0x50, 0x61, 0xcf, 0x88, 0x7d, 0x85, 0x07, 0x73, 0xab, 0xa3, 0x9b, 0xd7, 0x5f, 0x2e, 0xd7, 0xcc,
	0x0d, 0xbd, 0x4f, 0x92, 0x55, 0xc9, 0x6b, 0xbb, 0x8c, 0x33, 0x5d, 0x25, 0x55, 0x99, 0xad, 0x31,
	0xdd, 0x54, 0xe5, 0x3d, 0xfe, 0x58, 0x26, 0x45, 0xb1, 0x0d, 0xbf, 0xc9, 0x72, 0xe8, 0x97, 0xff,
	0xed, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0x7c, 0x08, 0xfc, 0x3c, 0x03, 0x00, 0x00,
}
