// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tags/tags.proto

package tags

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RatePostRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Post                 *Post    `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatePostRequest) Reset()         { *m = RatePostRequest{} }
func (m *RatePostRequest) String() string { return proto.CompactTextString(m) }
func (*RatePostRequest) ProtoMessage()    {}
func (*RatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f12757892b65802, []int{0}
}

func (m *RatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatePostRequest.Unmarshal(m, b)
}
func (m *RatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatePostRequest.Marshal(b, m, deterministic)
}
func (m *RatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatePostRequest.Merge(m, src)
}
func (m *RatePostRequest) XXX_Size() int {
	return xxx_messageInfo_RatePostRequest.Size(m)
}
func (m *RatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RatePostRequest proto.InternalMessageInfo

func (m *RatePostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RatePostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type Post struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Tags                 []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Likes                int32    `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f12757892b65802, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Post) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

type TagBaseResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagBaseResponse) Reset()         { *m = TagBaseResponse{} }
func (m *TagBaseResponse) String() string { return proto.CompactTextString(m) }
func (*TagBaseResponse) ProtoMessage()    {}
func (*TagBaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f12757892b65802, []int{2}
}

func (m *TagBaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagBaseResponse.Unmarshal(m, b)
}
func (m *TagBaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagBaseResponse.Marshal(b, m, deterministic)
}
func (m *TagBaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagBaseResponse.Merge(m, src)
}
func (m *TagBaseResponse) XXX_Size() int {
	return xxx_messageInfo_TagBaseResponse.Size(m)
}
func (m *TagBaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagBaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagBaseResponse proto.InternalMessageInfo

func (m *TagBaseResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TagBaseResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RatePostRequest)(nil), "ffv.tags.RatePostRequest")
	proto.RegisterType((*Post)(nil), "ffv.tags.Post")
	proto.RegisterType((*TagBaseResponse)(nil), "ffv.tags.TagBaseResponse")
}

func init() { proto.RegisterFile("tags/tags.proto", fileDescriptor_0f12757892b65802) }

var fileDescriptor_0f12757892b65802 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xb4, 0x69, 0xda, 0xce, 0x0b, 0x6f, 0x5f, 0x16, 0xd1, 0xd5, 0x53, 0xc8, 0x29,
	0x22, 0x24, 0x50, 0x6f, 0x5e, 0x84, 0xd2, 0x8b, 0x20, 0x22, 0xb1, 0x27, 0x2f, 0xb2, 0x4d, 0x37,
	0xc9, 0xd2, 0x3f, 0x1b, 0x77, 0x26, 0x05, 0xbf, 0x83, 0x67, 0x3f, 0xaf, 0xec, 0xae, 0x45, 0xe9,
	0xd5, 0x4b, 0x98, 0xdf, 0x3c, 0xd9, 0x67, 0x98, 0x67, 0x60, 0x42, 0xa2, 0xc6, 0xdc, 0x7e, 0xb2,
	0xd6, 0x68, 0xd2, 0x6c, 0x54, 0x55, 0xfb, 0xcc, 0x72, 0xf2, 0x00, 0x93, 0x42, 0x90, 0x7c, 0xd4,
	0x48, 0x85, 0x7c, 0xed, 0x24, 0x12, 0x3b, 0x83, 0x61, 0x87, 0xd2, 0xbc, 0xa8, 0x15, 0x0f, 0xe2,
	0x20, 0x1d, 0x17, 0x91, 0xc5, 0xbb, 0x15, 0x4b, 0x20, 0x6c, 0x35, 0x12, 0xef, 0xc5, 0x41, 0xfa,
	0x77, 0xfa, 0x2f, 0x3b, 0x98, 0x64, 0xee, 0xb5, 0xd3, 0x92, 0xf7, 0x00, 0x42, 0x8b, 0xec, 0x3f,
	0xf4, 0x3b, 0xb3, 0xf9, 0x72, 0xb0, 0x25, 0x63, 0x10, 0xda, 0xbf, 0x79, 0x2f, 0xee, 0xa7, 0xe3,
	0xc2, 0xd5, 0xec, 0x14, 0x22, 0xd4, 0x9d, 0x29, 0x25, 0xef, 0xfb, 0x51, 0x9e, 0x6c, 0x5f, 0x74,
	0xd4, 0x68, 0xc3, 0x43, 0xdf, 0xf7, 0xc4, 0x38, 0x0c, 0x4b, 0xbd, 0x23, 0xb9, 0x23, 0x3e, 0x70,
	0xc2, 0x01, 0xd9, 0x09, 0x0c, 0x36, 0x6a, 0x2d, 0x91, 0x47, 0x71, 0x90, 0x0e, 0x0a, 0x0f, 0xc9,
	0x2d, 0x4c, 0x16, 0xa2, 0x9e, 0x09, 0x94, 0x85, 0xc4, 0x56, 0xef, 0xd0, 0x59, 0x23, 0x09, 0xea,
	0xf0, 0xb0, 0x9d, 0x27, 0x6b, 0x20, 0x8d, 0xd1, 0xc6, 0xad, 0x37, 0x2e, 0x3c, 0x4c, 0x3f, 0x02,
	0x80, 0x85, 0xa8, 0x9f, 0xa4, 0xd9, 0xab, 0x52, 0xb2, 0x19, 0x8c, 0xee, 0xd5, 0xda, 0xc5, 0xc5,
	0xce, 0xbf, 0x03, 0x38, 0x8a, 0xf0, 0xe2, 0x87, 0x74, 0x34, 0x3e, 0xf9, 0xc3, 0xe6, 0x00, 0x73,
	0x85, 0xbf, 0x74, 0x99, 0x5d, 0x3d, 0x5f, 0x36, 0x44, 0x2d, 0xde, 0xe4, 0x79, 0xad, 0xa8, 0xe9,
	0x96, 0x59, 0xa9, 0xb7, 0xf9, 0x56, 0x95, 0x8d, 0x14, 0x9b, 0xad, 0x5a, 0xcb, 0xb7, 0x65, 0x5e,
	0x55, 0x7b, 0x77, 0xf5, 0x65, 0xe4, 0xce, 0x7e, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x32, 0xbd,
	0x9b, 0x6f, 0x09, 0x02, 0x00, 0x00,
}
